### ISSUE TITLE
Calendar displaying out of order

### ISSUE THREAD

**Issue by saelili** [FCCColumbus/F3C_Website#100]
Our events page is not displaying in order. Events should display according to their date. This can be fixed using the Eventbrite API. 
https://www.eventbrite.com/platform/api#/reference/event

Long term we may want to use the new free Code Camp forum or Meetup to retrieve event info. https://www.freecodecamp.org/forum/c/united-states-study-groups/columbus/l/calendar

**Comment by jwoo92** [comment]
@saelili We should handle this on the server, not frontend.

**Comment by saelili** [comment]
@jwoo92 Thanks. Noticed this last night and someone offered to work on it. Wanted to quickly make a ticket for them when I got home but did not think it through.
