### ISSUE TITLE
Add Calendar section of upcoming events

### ISSUE THREAD

**Issue by DanStockham** [FCCColumbus/F3C_Website#16]
A simple list of events pulled from Eventbrite's API. 

Sorted by the latest date. Each event card is clickable and directs the user to the event page on Eventbrite in a new tab.

**Comment by dannyrb** [comment]
Curious to hear your approach for this. Let me know if you want to noodle on this together.

**Comment by DanStockham** [comment]
@dannyrb We already have implemented a solution for the calendar page. It's safe to close this issue
https://github.com/FCCColumbus/F3C_Website/pull/25

However, there is room for improvement and you're more than welcome to add or make changes :)
