### ISSUE TITLE
Content in Call To Action button is breaking out

### ISSUE THREAD

**Issue by DanStockham** [FCCColumbus/F3C_Website#19]
The Call To Action button is breaking out of the button container

## Expected Behavior: 
![image](https://user-images.githubusercontent.com/11827054/31319967-830d1184-ac3a-11e7-8d18-218257764a2b.png)

## Actual Behavior:
![image](https://user-images.githubusercontent.com/11827054/31319979-b65108f2-ac3a-11e7-9a49-8d282320e270.png)

**Comment by dannyrb** [comment]
I'm only seeing this on resolutions < 325px (that's really small). Do we have an official "lowest supported resolution"? You'll sometimes see `max-width: 320px` on the body to set that lower bound. It varies by company, but this number is usually between `310px` and `400px`.

If we're aiming for lower, we may need to cut some of the text, or allow the button's height to grow to accommodate a second line. If we're targeting > `325px`, we could solve the perceived problem with a body `min-width`

**Comment by DanStockham** [comment]
Merged to dev
