### ISSUE TITLE
Admin panel in portrait mode

### ISSUE THREAD

**Issue by DanStockham** [FCCColumbus/F3C_Website#20]
While in portrait mode within mobile view, the avatar gallery maintains its current size and overlaps each other.

![image](https://user-images.githubusercontent.com/11827054/31320079-61d6201c-ac3c-11e7-9a10-5d6654db7a8e.png)

**Comment by dannyrb** [comment]
I can't seem to reproduce this bug. Does it still exist? What specifics are needed to recreate it?

**Comment by DanStockham** [comment]
@dannyrb I think your most recent pull request may of been what resolved the issue. I'm going to close this for now
