### ISSUE TITLE
Mobile Navbar will not close when clicking logo

### ISSUE THREAD

**Issue by DanStockham** [FCCColumbus/F3C_Website#24]
In mobile view and while the navbar is extended, if you click on logo to be taken back to the homepage, the navbar doesn't retract back. 

The expected behavior would toggle the navbar to being closed when the user clicks on the logo.

![image](https://user-images.githubusercontent.com/11827054/31473657-f77350de-aec3-11e7-83de-31c272c267c1.png)

![image](https://user-images.githubusercontent.com/11827054/31473683-16035dc8-aec4-11e7-8bfc-f705a9d0fa36.png)

**Comment by dannyrb** [comment]
@jwoo92 it looks like a PR was merged to address this issue. It should be good for a close 👍

**Comment by DanStockham** [comment]
@dannyrb Rightly so
