### ISSUE TITLE
Calendar page suggestions

### ISSUE THREAD

**Issue by dannyrb** [FCCColumbus/F3C_Website#52]
## Current Calendar Page:

![https://i.imgur.com/65Mh7eT.png](https://i.imgur.com/65Mh7eT.png)

## Suggested Updates:

_While results are loading_
* Centered, larger, more prominent loading text
* Loading animation/spinner

_No Results_
* Center "No Events to Display" text
* Increase font size
* Make italic
* Lighten font-color
* Provide a happier, more positive, message
    * > There are no upcoming events scheduled at the moment, but be sure to check back! We're always planning new and fun events. `<insert hip cool emoji or GIF here>`

_After results are loaded_
* Show previous X events
    * When no new events exist, it provides a "pulse" on how active our group is. Otherwise, we could appear to be an inactive chapter of FCC
* Potentially provide metrics/counters for:
    - Number of events in past year
    - Number of unique members that have attended events
    - Days since last event, and days until next event
* Potentially show categories of events so visitors know what kind of events to expect, and how frequently they occur

**Comment by Kavinci** [comment]
Copied from Slack conversation:
Info graphics for those metrics would be cool too. Maybe have a graph to show attendance or from eventbrite we might be able to pull tickets "sold"


Caleb Cox [2 days ago]
@kavinci I don't contribute to the site myself but I thought this was an interesting suggestion so I wanted to look into it. It appears this would be possible with Eventbrites API.

https://www.eventbrite.com/developer/v3/response_formats/order/#ebapi-std:format-order
Eventbrite
Order - Eventbrite Developer Center
Eventbrite brings people together through live experiences. Discover events that match your passions, or create your own with online ticketing tools.
 


Kent Utterback [2 days ago]
That is awesome! A count would do just fine but I think having names and email addresses on a private side (admin side) for a post event reach out would be helpful. Also, the attendee object https://www.eventbrite.com/developer/v3/response_formats/attendee/#ebapi-std:format-attendee would be a cool way to track attendance and maybe award badges to user accounts
Eventbrite
Attendee - Eventbrite Developer Center
Eventbrite brings people together through live experiences. Discover events that match your passions, or create your own with online ticketing tools.
